name: unit-tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: バックエンドの依存関係をインストールし、テストを実行
        run: cd backend && npm install && npm test

  deploy:
      runs-on: ubuntu-latest
      needs: test  # テストが成功した場合のみデプロイ

      steps:
        - name: リポジトリをチェックアウト
          uses: actions/checkout@v4

        - name: SSH鍵をセットアップ
          run: |
            # ディレクトリ作成を確認
            mkdir -p ~/.ssh
            echo "ディレクトリ作成後: "
            ls -l ~/.ssh
            # 秘密鍵のデコードと確認
            echo "${{ secrets.VPS_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
            echo "秘密鍵の配置後: "
            ls -l ~/.ssh
            # ファイル権限を確認
            chmod 600 ~/.ssh/id_rsa
            echo "ファイル権限設定後: "
            ls -l ~/.ssh/id_rsa
        
        - name: backendディレクトリのみをVPSへデプロイ
          run: |
            echo "rsync 実行前の状態:"
            ls -l ~/.ssh/id_rsa
            # rsync コマンドの実行
            rsync -avz -vv --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./backend/ root@${{ secrets.VPS_HOST }}:/UMA-DB/backend/ --progress
            echo "rsync 実行後の状態:"
        